user:
  username: "root"
  email: "petre.v.alexandru@gmail.com"
  password: "rootpassword"

serviceType: ClusterIP

ingress:
  enabled: true
  hostName: polyaxon.mlfarm.net
  tls:
  - secretName: mlfarm-tls
    hosts:
      - polyaxon.mlfarm.net
  annotations:
    nginx.ingress.kubernetes.io/app-root: /polyaxon
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 4G

broker: redis

rabbitmq-ha:
  enabled: false

postgresql:
  enabled: false

externalServices:
  postgresql:
    user: polyaxon
    password: polyaxon
    database: polyaxon
    host: 192.168.0.178

persistence:
  data:
    coco:
      mountPath: "/data/coco"
      existingClaim: data-coco
    imgnet:
      mountPath: "/data/imgnet"
      existingClaim: data-imgnet
    kaggle:
      mountPath: "/data/kaggle"
      existingClaim: data-kaggle
    research:
      mountPath: "/data/research"
      existingClaim: data-research
  outputs:
    outputs:
      mountPath: "/artefacts"
      existingClaim: artefacts
  logs:
    mountPath: "/logs"
    existingClaim: logs
  repos:
    mountPath: "/repos"
    existingClaim: repos
