apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-sql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/polyaxon/sql"
