rbac:
  enabled: false

serviceType: NodePort

broker: redis
rabbitmq-ha:
  enabled: false

postgresql:
  persistence:
    enabled: false

externalServices:
  postgresql:
    user: polyaxon
    password: polyaxon
    database: polyaxon
    host: 192.168.0.178

persistence:
  data:
    coco:
      mountPath: "/data/coco"
      existingClaim: data-coco
    imgnet:
      mountPath: "/data/imgnet"
      existingClaim: data-imgnet
    kaggle:
      mountPath: "/data/kaggle"
      existingClaim: data-kaggle
    research:
      mountPath: "/data/research"
      existingClaim: data-research
  outputs:
    outputs:
      mountPath: "/artefacts"
      existingClaim: artefacts
  logs:
    mountPath: "/logs"
    existingClaim: logs
  repos:
    mountPath: "/repos"
    existingClaim: repos